
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AT COMMA CONNECT CONTENT CREATE EXIT IDENTIFIER IP_V4 KILL LP MESSAGE PORT REQUEST RESPONSE RP SEND TO WAIT\n    eval : empty\n         | connect_client\n         | create_server\n         | send_message\n         | wait_response\n         | wait_request\n         | send_response\n         | close\n         | kill_connection\n    \n    empty :\n    \n    connect_client : CONNECT IDENTIFIER TO PORT COMMA IP_V4\n                   | CONNECT IDENTIFIER TO LP PORT COMMA IP_V4 RP\n    \n    send_message : SEND MESSAGE CONTENT\n                 | SEND MESSAGE LP CONTENT RP\n    \n    create_server : CREATE IDENTIFIER AT PORT COMMA IP_V4\n                  | CREATE IDENTIFIER AT LP PORT COMMA IP_V4 RP\n    \n    wait_response : WAIT RESPONSE\n    \n    wait_request : WAIT REQUEST\n    \n    send_response : SEND RESPONSE MESSAGE CONTENT\n                  | SEND RESPONSE MESSAGE LP CONTENT RP\n    \n    close : EXIT\n    \n    kill_connection : KILL IDENTIFIER\n    '
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,7,8,9,10,15,21,22,23,26,34,40,42,44,46,49,50,],[-10,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-21,-17,-18,-22,-13,-19,-14,-11,-15,-20,-12,-16,]),'CONNECT':([0,],[11,]),'CREATE':([0,],[12,]),'SEND':([0,],[13,]),'WAIT':([0,],[14,]),'EXIT':([0,],[15,]),'KILL':([0,],[16,]),'IDENTIFIER':([11,12,16,],[17,18,23,]),'MESSAGE':([13,20,],[19,28,]),'RESPONSE':([13,14,],[20,21,]),'REQUEST':([14,],[22,]),'TO':([17,],[24,]),'AT':([18,],[25,]),'CONTENT':([19,27,28,35,],[26,33,34,41,]),'LP':([19,24,25,28,],[27,30,32,35,]),'PORT':([24,25,30,32,],[29,31,37,39,]),'COMMA':([29,31,37,39,],[36,38,43,45,]),'RP':([33,41,47,48,],[40,46,49,50,]),'IP_V4':([36,38,43,45,],[42,44,47,48,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'eval':([0,],[1,]),'empty':([0,],[2,]),'connect_client':([0,],[3,]),'create_server':([0,],[4,]),'send_message':([0,],[5,]),'wait_response':([0,],[6,]),'wait_request':([0,],[7,]),'send_response':([0,],[8,]),'close':([0,],[9,]),'kill_connection':([0,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> eval","S'",1,None,None,None),
  ('eval -> empty','eval',1,'p_eval','DoingNothing_Parser_IntermmediateCode_yacc.py',15),
  ('eval -> connect_client','eval',1,'p_eval','DoingNothing_Parser_IntermmediateCode_yacc.py',16),
  ('eval -> create_server','eval',1,'p_eval','DoingNothing_Parser_IntermmediateCode_yacc.py',17),
  ('eval -> send_message','eval',1,'p_eval','DoingNothing_Parser_IntermmediateCode_yacc.py',18),
  ('eval -> wait_response','eval',1,'p_eval','DoingNothing_Parser_IntermmediateCode_yacc.py',19),
  ('eval -> wait_request','eval',1,'p_eval','DoingNothing_Parser_IntermmediateCode_yacc.py',20),
  ('eval -> send_response','eval',1,'p_eval','DoingNothing_Parser_IntermmediateCode_yacc.py',21),
  ('eval -> close','eval',1,'p_eval','DoingNothing_Parser_IntermmediateCode_yacc.py',22),
  ('eval -> kill_connection','eval',1,'p_eval','DoingNothing_Parser_IntermmediateCode_yacc.py',23),
  ('empty -> <empty>','empty',0,'p_empty','DoingNothing_Parser_IntermmediateCode_yacc.py',28),
  ('connect_client -> CONNECT IDENTIFIER TO PORT COMMA IP_V4','connect_client',6,'p_connect_client','DoingNothing_Parser_IntermmediateCode_yacc.py',34),
  ('connect_client -> CONNECT IDENTIFIER TO LP PORT COMMA IP_V4 RP','connect_client',8,'p_connect_client','DoingNothing_Parser_IntermmediateCode_yacc.py',35),
  ('send_message -> SEND MESSAGE CONTENT','send_message',3,'p_send_message','DoingNothing_Parser_IntermmediateCode_yacc.py',68),
  ('send_message -> SEND MESSAGE LP CONTENT RP','send_message',5,'p_send_message','DoingNothing_Parser_IntermmediateCode_yacc.py',69),
  ('create_server -> CREATE IDENTIFIER AT PORT COMMA IP_V4','create_server',6,'p_create_server','DoingNothing_Parser_IntermmediateCode_yacc.py',93),
  ('create_server -> CREATE IDENTIFIER AT LP PORT COMMA IP_V4 RP','create_server',8,'p_create_server','DoingNothing_Parser_IntermmediateCode_yacc.py',94),
  ('wait_response -> WAIT RESPONSE','wait_response',2,'p_wait_response','DoingNothing_Parser_IntermmediateCode_yacc.py',133),
  ('wait_request -> WAIT REQUEST','wait_request',2,'p_wait_request','DoingNothing_Parser_IntermmediateCode_yacc.py',152),
  ('send_response -> SEND RESPONSE MESSAGE CONTENT','send_response',4,'p_send_response','DoingNothing_Parser_IntermmediateCode_yacc.py',172),
  ('send_response -> SEND RESPONSE MESSAGE LP CONTENT RP','send_response',6,'p_send_response','DoingNothing_Parser_IntermmediateCode_yacc.py',173),
  ('close -> EXIT','close',1,'p_close','DoingNothing_Parser_IntermmediateCode_yacc.py',194),
  ('kill_connection -> KILL IDENTIFIER','kill_connection',2,'p_kill_connection','DoingNothing_Parser_IntermmediateCode_yacc.py',201),
]
